---
roles:
  - name: yunhai20082008.ansible-role-mysql
    src: https://github.com/yunhai20082008/ansible-role-mysql.git
    version: master

collections:
  # - community.general
  - name: community.mysql
    version: "3.7.2"
  # - community.postgresql
  # - community.seboolean
  
